export { cafes } from "./data/cafes";
export { pizzas } from "./data/pizzas";
export { malteadas } from "./data/malteadas";
export { galletas } from "./data/galletas";
export {default as CreateDishsForm} from "./components/CreateDishsForm"
export {default as DishDetails} from "./components/DishDetails"
export {default as DishEditForm} from "./components/DishEditForm"
export {default as CreateOrderForm} from "../orders/components/CreateOrderForm"
export {default as OrderDetails} from "../orders/components/OrderDetails"
export {default as OrderEditForm} from "../orders/components/OrderEditForm"
export {default as PermissionsForm} from "../permissions/components/PermissionsForm"